### ISSUE TITLE
Does it support Deta Space micros?

### ISSUE THREAD

**Issue by pickaxe828** [jnsougata/discohook#1]
Hi! Just tried your library by following your instructions with using Deta Space
But I cannot save the changes when I inputted the URL in the Endpoint URL box:
![image](https://user-images.githubusercontent.com/41852594/219846331-3cc0d081-20bd-4d43-b0ab-c91d5e587966.png)
What should I do?

**Comment by jnsougata** [comment]
hey ... you have to add `/interactions` to public routes

**Comment by pickaxe828** [comment]
Oh it works now! I've just registered the command on the dashboard
But it is making this error now... How do I fix it?
![image](https://user-images.githubusercontent.com/41852594/219851272-68a157aa-e274-4051-9a4a-16dd3cabb5b5.png)

**Comment by jnsougata** [comment]
Can you share some logs? You can join our discord server for more help
https://discord.gg/a67HbpfTk8

**Comment by pickaxe828** [comment]
It is now fixed with help from the Discord guild! Thanks 🙏🏻!
